controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# fc_load_events:
#     path: /fc-load-events
#     controller: tattali.calendar.controller.ajax::loadEventsAction
#     methods: [POST]
